name: PR - Tests with Jest
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-note@v2
        with:
          node-version:14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
      - run: yarn
      - run: yarn jest